<a href="https://colab.research.google.com/github/Mayerli05Pinargote/HOLAMUNDO/blob/main/PracticaNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!python --version


Python 3.10.12


ARREGLO DE 1 DIMESION ARRAY (N;N;N)

In [ ]:
import numpy as np #importar
novio=np.array([3,33,333]) #declarar la dimesion
print(novio)
print (novio.shape)

[  3  33 333]
(3,)


In [ ]:
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print (b)
print(b[:,[2,3]])
#print (b)

#invertir
print (b)
print(b[:,[3,2]])
#print (b)


(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [120.   0.]]


In [ ]:
c=np.random.randint(low=4,high=12,size=(2,2))
d=np.random.randint(low=4,high=8,size=(2,2))

In [ ]:
c

array([[ 9, 11],
       [ 7,  7]])

In [ ]:
d

array([[7, 7],
       [4, 4]])

In [ ]:
aux=np.vstack((c,d)) #matriz vertical
print(aux)

[[ 9 11]
 [ 7  7]
 [ 7  7]
 [ 4  4]]


In [ ]:
aux=np.hstack((c,d)) #matriz horizontal
print(aux)

[[ 9 11  7  7]
 [ 7  7  4  4]]


In [ ]:
aux=np.vstack((c,d)) #matriz vertical
print(aux)

[[ 9 11]
 [ 7  7]
 [ 7  7]
 [ 4  4]]
