<a href="https://colab.research.google.com/github/Mayerli05Pinargote/HOLAMUNDO/blob/main/tareanumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

tarea

In [1]:
import numpy as np

print("NumPy version:", np.version.version)

pass

NumPy version: 1.22.4


In [2]:
#Create a 1D array of numbers from 0 to 9

arr = np.arange(10)
print(arr)
pass

[0 1 2 3 4 5 6 7 8 9]


In [3]:
#Create a 3×3 numpy array of all True’s
import numpy as np

arra = np.ones((3, 3), dtype=int)
arra = arr.astype(bool)
print(arr)
pass

[0 1 2 3 4 5 6 7 8 9]


In [8]:
#Extract all odd numbers from arr
import numpy as np
matriz = np.random.randint(1, 20, size=(5, 3))
print("Matriz original:")
print(matriz)

# Extraer los números impares de la matriz
impares = []
for i in range(len(matriz)):
    for j in range(len(matriz[i])):
        if matriz[i][j] % 2 != 0:
            impares.append(matriz[i][j])

print("Números impares:", impares)

pass

Matriz original:
[[15  5 15]
 [ 5 19 13]
 [13 11  6]
 [15 15  6]
 [13 10 16]]
Números impares: [15, 5, 15, 5, 19, 13, 13, 11, 15, 15, 13]


In [9]:
#Replace all odd numbers in arr with -1
import random

# Crear una matriz de 3x3 con números aleatorios entre 1 y 10
matriz = [[random.randint(1, 10) for j in range(3)] for i in range(3)]
print("Matriz de números aleatorios:")
for fila in matriz:
    print(fila)

# Extraer los números impares de la matriz y reemplazarlos por -1
for i in range(len(matriz)):
    for j in range(len(matriz[i])):
        if matriz[i][j] % 2 != 0:
            matriz[i][j] = -1

print("Matriz con números impares reemplazados por -1:")
for fila in matriz:
    print(fila)
pass

Matriz de números aleatorios:
[2, 2, 4]
[10, 9, 3]
[8, 5, 4]
Matriz con números impares reemplazados por -1:
[2, 2, 4]
[10, -1, -1]
[8, -1, 4]


In [10]:
#Convert a 1D array to a 2D array with 2 rows
arr = np.arange(10)
print(arr)
arr = arr.reshape(2, 5)
print(arr)
pass

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [11]:
#Stack arrays a and b vertically
import numpy as np
a = np.random.randint(1, 10, size=(3, 3))
b = np.random.randint(1, 10, size=(3, 3))

print("Matriz a:")
print(a)
print("Matriz b:")
print(b)

# Apilar verticalmente las dos matrices
c = np.vstack((a, b))

print("Matriz c:")
print(c)
print('----')
c=np.random.randint(low=4,high=12,size=(2,2))
d=np.random.randint(low=1,high=8,size=(2,2))
aux=np.vstack((c,d))
print(aux)
pass

Matriz a:
[[9 4 2]
 [6 5 6]
 [6 6 5]]
Matriz b:
[[3 9 3]
 [3 1 7]
 [3 5 9]]
Matriz c:
[[9 4 2]
 [6 5 6]
 [6 6 5]
 [3 9 3]
 [3 1 7]
 [3 5 9]]
----
[[ 8  7]
 [11  4]
 [ 6  7]
 [ 6  1]]


In [12]:
#Stack the arrays a and b horizontally
aux=np.hstack((c,d))
print(aux)
pass

[[ 8  7  6  7]
 [11  4  6  1]]


In [13]:
#Get all items between 5 and 10 from a
import numpy as np
arr = np.arange(10)
# Get all items between 5 and 10
result = arr[arr >= 5]
print(result)
pass

[5 6 7 8 9]


In [14]:
#How to make a python function that handles scalars to work on numpy arrays
 # Hint
# Desired Output:
# a = np.array([5, 7, 9, 8, 6, 4, 5])
# b = np.array([6, 3, 4, 8, 9, 7, 1])
# #> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])
import numpy as np

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
#maxx(a, b)
tmp=list()
for i in range(7):
  tmp.append(maxx(a[i],b[i]))
print(tmp)



[6, 7, 9, 8, 9, 7, 5]


In [15]:
#Swap columns 1 and 2 in the array arr
# Hint
# Desired Output:
# [[0 2 1]
#  [3 5 4]
#  [6 8 7]]
b=np.zeros((4,6))
b
print(b.shape)
print(b)
b[3,3]=120
print (b)
print(b[:,[2,3]])
#print (b)

#invertir
print (b)
print(b[:,[3,2]])
#print (b)
pass
 #[[0 1 2]
 #[3 4 5]
# [6 7 8]]


(4, 6)
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [  0. 120.]]
[[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0. 120.   0.   0.]]
[[  0.   0.]
 [  0.   0.]
 [  0.   0.]
 [120.   0.]]


In [16]:
#Create a 2D array of shape 5x3 to contain random decimal numbers between
# Crear una matriz de 5x3 con números decimales aleatorios entre 5 y 10
import numpy as np
matriz = [[np.random.uniform(5, 10) for j in range(3)] for i in range(5)]
print("Matriz de números decimales aleatorios:")
for fila in matriz:
    print(fila)
# The desired Output should be like the following one:
#  [[ 8.50061025  9.10531502  6.85867783]
#   [ 9.76262069  9.87717411  7.13466701]
#   [ 7.48966403  8.33409158  6.16808631]
#   [ 7.75010551  9.94535696  5.27373226]
#   [ 8.0850361   5.56165518  7.31244004]]

Matriz de números decimales aleatorios:
[5.361481517943216, 9.926591592423796, 7.972139665199014]
[5.065929352218227, 5.5879825293362, 9.094564068651259]
[7.413084655979306, 5.862367862749026, 9.929086401428414]
[6.941706421178846, 9.934754986759629, 9.054742552674938]
[7.70978309339621, 6.436039505059048, 6.803575725004676]
